[package]
name = "library_dev"
version = "0.1"
timeout = 20000

[dependencies]
stdlib = {git = "https://github.com/leanprover/stdlib.git", rev = "fe811868cde6d751f61b50e9e92f18868f8f371c"}
super = {git = "https://github.com/leanprover/super.git", rev = "3e1696001544818a42ce309c454268b7a14e9875"}
